### ISSUE TITLE
[Feature request] Ability to download raw log file

### ISSUE THREAD

**Issue by Dmitry221060** [Ridepad/uwu-logs#11]
While the parser can correctly parse and display a significant part of the log file, there are still cases when it fails to do so(some boss abilities not being present on the timeline, different ranks of healing spells being batched together under one heal spell effect, shields and absorbs not contributing to the healing total, etc). 
In such cases, having access to raw log file for further analysis is very helpful, especially on progression phase of a new raid. It would also make it easier to debug the parser and identify common failure points which would help to improve it further

**Comment by Ridepad** [comment]
add **download** after report link

`https://uwu-logs.xyz/reports/REPORT_ID/download`
