### ISSUE TITLE
missing instruction to run api_upload.py too

### ISSUE THREAD

**Issue by Dorian-Grim** [Ridepad/uwu-logs#7]
Missing instruction to run `api_upload.py` file along with `Z_SERVER.py`. Without the `api_upload.py` running the `/upload` route doesn't work. 

https://github.com/Ridepad/uwu-logs/blob/c939ef915a8833d9b7e0d17fd4471ed70f4d4bd3/README.md?plain=1#L15

**Comment by Ridepad** [comment]
https://github.com/Ridepad/uwu-logs/commit/cc91499a99bf0c06053ed42f832459d0fbac82b3
