### ISSUE TITLE
when running locally for the first time

### ISSUE THREAD

**Issue by Dorian-Grim** [Ridepad/uwu-logs#9]
When you run locally for the first time there's a bunch of errors related to the wgets for the 7z exes. The file names are here:
https://github.com/Ridepad/uwu-logs/blob/c939ef915a8833d9b7e0d17fd4471ed70f4d4bd3/api_7z.py#L23-L25

Uploading only works after the files are downloaded.
![image](https://github.com/user-attachments/assets/f338367b-9cda-4678-b831-431c3d7abefc)

I don't see why you shouldn't make files already available in the repo.

**Comment by Ridepad** [comment]
fixed in https://github.com/Ridepad/uwu-logs/commit/c939ef915a8833d9b7e0d17fd4471ed70f4d4bd3

not gonna upload unnecessary files to repo
